version: '3.9'

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"  
  #   environment:
  #     NODE_ENV: development
  #     REACT_APP_BACKEND_SERVER: http://localhost:8087/api/

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/demo?sslmode=disable
  #     TZ: Asia/Bangkok 
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      TZ: Asia/Bangkok
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dpu.ac.th
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  db:
